### PR TITLE
feat: use new session impl

### PR DESCRIPTION
**Pull request by gengjiawen**
@fuergaosi233

### CODE REVIEW

**Comment by fuergaosi233** [comment]
I want it to be able to log in with an account and password 🤔 we need add auth.

**Comment by gengjiawen** [comment]
> I want it to be able to log in with an account and password 🤔 we need add auth.

The email login still exist, I only make the check not a must.

**Comment by fuergaosi233** [comment]
> > I want it to be able to log in with an account and password 🤔 we need add auth.
> 
> The email login still exist, I only make the check not a must.

4.x does not include browser ChatGPT .

**Comment by gengjiawen** [comment]
> > > I want it to be able to log in with an account and password 🤔 we need add auth.
> > 
> > 
> > The email login still exist, I only make the check not a must.
> 
> 4.x does not include browser ChatGPT .

I have switch to `waylaidwanderer/node-chatgpt-api` for token. PTAL.

**Comment by gengjiawen** [comment]
For anyone want to try:

For how generate session, all you need is your access token from https://chat.openai.com/api/auth/session
```
docker run -d --name chatgpt-api-single -e HOST=0.0.0.0 -e SESSION_TOKEN=your_token -p 4000:4000 -v $PWD/docker:/app/data gengjiawen/chatgpt
```

**Comment by gengjiawen** [comment]
close in favor of https://github.com/bytemate/chatapi-single/pull/34

**Pull request closed without merging**
